-- Opcional: seed da tabela CRM no padrão master-card-v1.
-- Compatível com as regras:
-- - layout fixo (master-card-v1)
-- - logo fixo no canto inferior direito

insert into public.crm_message_templates (
  slug,
  title,
  category,
  description,
  subject_type,
  message_template,
  theme_key,
  layout_key,
  logo_position,
  is_active,
  sort_order
)
values
  (
    'aniversario-cliente',
    'Feliz Aniversário!',
    'relacionamento',
    'Template de aniversário do cliente',
    'cliente',
    E'{{cliente_nome}},\n\nQue seu dia seja incrível!\nDesejo muita saúde, felicidade\ne momentos inesquecíveis.\n\nQue sua próxima viagem\nseja ainda mais especial!\n\nCom carinho\n{{consultor_nome}}\nConsultor de viagens',
    'birthday-elegant',
    'master-card-v1',
    'bottom-right',
    true,
    1
  ),
  (
    'dia-das-mulheres',
    'Feliz Dia das Mulheres!',
    'comemorativa',
    'Template de Dia das Mulheres',
    'cliente',
    E'{{cliente_nome}},\n\nDesejo que seu dia seja repleto\nde amor, inspiração\ne momentos especiais.\n\nVocê merece o melhor!\n\nCom carinho\n{{consultor_nome}}\nConsultor de viagens',
    'womens-day-soft',
    'master-card-v1',
    'bottom-right',
    true,
    2
  ),
  (
    'dia-das-maes',
    'Feliz Dia das Mães!',
    'comemorativa',
    'Template de Dia das Mães',
    'cliente',
    E'{{cliente_nome}},\n\nHoje celebramos o amor,\no carinho e os momentos\nmais especiais da vida.\n\nDesejo um dia lindo para você!\n\nCom carinho\n{{consultor_nome}}\nConsultor de viagens',
    'mothers-day-floral',
    'master-card-v1',
    'bottom-right',
    true,
    3
  ),
  (
    'feliz-natal',
    'Feliz Natal!',
    'sazonal',
    'Template de Natal',
    'cliente',
    E'{{cliente_nome}},\n\nQue o Natal traga paz,\nalegria e momentos especiais\nao lado de quem você ama.\n\nQue o próximo ano seja repleto\nde novas viagens!\n\nCom carinho\n{{consultor_nome}}\nConsultor de viagens',
    'christmas-gold',
    'master-card-v1',
    'bottom-right',
    true,
    4
  ),
  (
    'feliz-ano-novo',
    'Feliz Ano Novo!',
    'sazonal',
    'Template de Ano Novo',
    'cliente',
    E'{{cliente_nome}},\n\nQue o novo ano traga\nnovas conquistas,\nsonhos realizados\ne muitas viagens incríveis!\n\nCom carinho\n{{consultor_nome}}\nConsultor de viagens',
    'new-year-celebration',
    'master-card-v1',
    'bottom-right',
    true,
    5
  ),
  (
    'feliz-pascoa',
    'Feliz Páscoa!',
    'sazonal',
    'Template de Páscoa',
    'cliente',
    E'{{cliente_nome}},\n\nQue esta Páscoa seja marcada\npor paz, renovação\ne momentos felizes.\n\nQue nunca faltem motivos\npara celebrar!\n\nCom carinho\n{{consultor_nome}}\nConsultor de viagens',
    'easter-pastel',
    'master-card-v1',
    'bottom-right',
    true,
    6
  ),
  (
    'dia-dos-pais',
    'Feliz Dia dos Pais!',
    'comemorativa',
    'Template de Dia dos Pais',
    'cliente',
    E'{{cliente_nome}},\n\nHoje celebramos aqueles\nque inspiram, protegem\ne deixam marcas especiais.\n\nDesejo um dia incrível para você!\n\nCom carinho\n{{consultor_nome}}\nConsultor de viagens',
    'fathers-day-classic',
    'master-card-v1',
    'bottom-right',
    true,
    7
  ),
  (
    'dia-dos-namorados',
    'Feliz Dia dos Namorados!',
    'comemorativa',
    'Template de Dia dos Namorados',
    'cliente',
    E'{{cliente_nome}},\n\nViajar é ainda melhor\nquando compartilhamos momentos\ncom quem amamos.\n\nDesejo uma data linda para você!\n\nCom carinho\n{{consultor_nome}}\nConsultor de viagens',
    'valentines-romantic',
    'master-card-v1',
    'bottom-right',
    true,
    8
  ),
  (
    'dia-do-cliente',
    'Feliz Dia do Cliente!',
    'relacionamento',
    'Template de Dia do Cliente',
    'cliente',
    E'{{cliente_nome}},\n\nHoje queremos agradecer\npela sua confiança e parceria.\n\nÉ um prazer fazer parte\ndas suas histórias de viagem!\n\nCom carinho\n{{consultor_nome}}\nConsultor de viagens',
    'client-day-premium',
    'master-card-v1',
    'bottom-right',
    true,
    9
  ),
  (
    'cliente-vip',
    'Cliente VIP',
    'fidelizacao',
    'Template para cliente VIP',
    'cliente',
    E'{{cliente_nome}},\n\nVocê é um cliente muito especial\npara nós.\n\nObrigado pela sua confiança\ne por fazer parte da nossa história.\n\nCom carinho\n{{consultor_nome}}\nConsultor de viagens',
    'vip-gold',
    'master-card-v1',
    'bottom-right',
    true,
    10
  ),
  (
    'cliente-premium',
    'Atendimento Premium para você',
    'fidelizacao',
    'Template para cliente premium',
    'cliente',
    E'{{cliente_nome}},\n\nVocê faz parte de um grupo\nde clientes especiais\nque valorizamos muito.\n\nConte sempre conosco!\n\nCom carinho\n{{consultor_nome}}\nConsultor de viagens',
    'premium-elegant',
    'master-card-v1',
    'bottom-right',
    true,
    11
  ),
  (
    'cliente-inativo',
    'Sentimos sua falta',
    'reativacao',
    'Template para reativação de cliente',
    'cliente',
    E'{{cliente_nome}},\n\nFaz um tempo que não\nplanejamos uma viagem juntos.\n\nQuando quiser pensar no próximo destino,\nestarei por aqui para ajudar.\n\nCom carinho\n{{consultor_nome}}\nConsultor de viagens',
    'inactive-soft-recovery',
    'master-card-v1',
    'bottom-right',
    true,
    12
  ),
  (
    'boas-vindas',
    'Seja bem-vindo!',
    'onboarding',
    'Template de boas-vindas',
    'cliente',
    E'{{cliente_nome}},\n\nÉ um prazer ter você conosco.\n\nEstamos prontos para ajudar\na transformar seus planos\nem viagens inesquecíveis.\n\nConte comigo!\n\n{{consultor_nome}}\nConsultor de viagens',
    'welcome-clean',
    'master-card-v1',
    'bottom-right',
    true,
    13
  ),
  (
    'mensagem-surpresa',
    'Uma mensagem especial para você',
    'relacionamento',
    'Template de mensagem surpresa',
    'cliente',
    E'{{cliente_nome}},\n\nPassando para desejar\numa ótima semana\ne lembrar que estou à disposição\npara sua próxima viagem.\n\nCom carinho\n{{consultor_nome}}\nConsultor de viagens',
    'surprise-soft',
    'master-card-v1',
    'bottom-right',
    true,
    14
  ),
  (
    'pos-viagem-feedback',
    'Como foi sua viagem?',
    'pos-venda',
    'Template de pós-viagem e feedback',
    'cliente',
    E'{{cliente_nome}},\n\nEspero que sua viagem\ntenha sido incrível!\n\nSe quiser compartilhar sua experiência,\nserá um prazer ouvir você.\n\nCom carinho\n{{consultor_nome}}\nConsultor de viagens',
    'post-trip-light',
    'master-card-v1',
    'bottom-right',
    true,
    15
  ),
  (
    'retorno-de-viagem',
    'Bem-vindo de volta!',
    'pos-venda',
    'Template de retorno de viagem',
    'cliente',
    E'{{cliente_nome}},\n\nEspero que seu retorno\ntenha sido tranquilo\ne que a viagem tenha deixado\nótimas lembranças.\n\nCom carinho\n{{consultor_nome}}\nConsultor de viagens',
    'travel-return-soft',
    'master-card-v1',
    'bottom-right',
    true,
    16
  ),
  (
    'pre-embarque',
    'Sua viagem está chegando!',
    'jornada',
    'Template de pré-embarque',
    'cliente',
    E'{{cliente_nome}},\n\nSua viagem está chegando\ne quero desejar\num excelente embarque\ne uma experiência maravilhosa.\n\nConte comigo no que precisar!\n\n{{consultor_nome}}\nConsultor de viagens',
    'pre-embark-clean',
    'master-card-v1',
    'bottom-right',
    true,
    17
  ),
  (
    'contagem-regressiva',
    'Falta pouco!',
    'jornada',
    'Template de contagem regressiva',
    'cliente',
    E'{{cliente_nome}},\n\nEstá chegando o momento\nda sua próxima viagem.\n\nQue a expectativa já esteja trazendo\naquela sensação boa\nde viver algo especial!\n\nCom carinho\n{{consultor_nome}}\nConsultor de viagens',
    'countdown-travel',
    'master-card-v1',
    'bottom-right',
    true,
    18
  ),
  (
    'aniversario-primeira-compra',
    'Celebrando sua primeira compra conosco!',
    'relacionamento',
    'Template de aniversário da primeira compra',
    'cliente',
    E'{{cliente_nome}},\n\nHoje celebramos um momento especial:\no aniversário da sua primeira compra conosco.\n\nObrigado por confiar no nosso trabalho!\n\nCom carinho\n{{consultor_nome}}\nConsultor de viagens',
    'anniversary-purchase',
    'master-card-v1',
    'bottom-right',
    true,
    19
  ),
  (
    'aniversario-primeira-viagem',
    'Um marco especial da sua viagem',
    'pos-venda',
    'Template de aniversário da primeira viagem',
    'cliente',
    E'{{cliente_nome}},\n\nHoje lembramos com carinho\nda sua primeira viagem conosco.\n\nFoi um prazer fazer parte\ndesse momento especial.\n\nCom carinho\n{{consultor_nome}}\nConsultor de viagens',
    'anniversary-trip',
    'master-card-v1',
    'bottom-right',
    true,
    20
  ),
  (
    'sugestao-destino',
    'Tenho uma sugestão para você',
    'oportunidade',
    'Template de sugestão de destino',
    'cliente',
    E'{{cliente_nome}},\n\nSeparei uma sugestão de destino\nque pode combinar muito com você.\n\nSe quiser, posso te mostrar\nopções e valores.\n\nCom carinho\n{{consultor_nome}}\nConsultor de viagens',
    'travel-opportunity',
    'master-card-v1',
    'bottom-right',
    true,
    21
  ),
  (
    'promocao-exclusiva',
    'Oferta especial para você',
    'campanha',
    'Template de promoção exclusiva',
    'cliente',
    E'{{cliente_nome}},\n\nSeparei uma condição especial\nque pode ser perfeita\npara sua próxima viagem.\n\nSe quiser, te envio os detalhes.\n\nCom carinho\n{{consultor_nome}}\nConsultor de viagens',
    'exclusive-offer',
    'master-card-v1',
    'bottom-right',
    true,
    22
  ),
  (
    'upgrade-vip',
    'Uma experiência ainda mais especial',
    'fidelizacao',
    'Template de upgrade VIP',
    'cliente',
    E'{{cliente_nome}},\n\nQuero te apresentar\numa possibilidade de upgrade\npara tornar sua próxima viagem\nainda mais completa.\n\nCom carinho\n{{consultor_nome}}\nConsultor de viagens',
    'vip-upgrade',
    'master-card-v1',
    'bottom-right',
    true,
    23
  ),
  (
    'indicacao-cliente',
    'Indique alguém especial',
    'relacionamento',
    'Template de indicação de cliente',
    'cliente',
    E'{{cliente_nome}},\n\nSe você conhece alguém\nque também ama viajar,\nserá um prazer atender essa indicação\ncom o mesmo cuidado.\n\nObrigado pela confiança!\n\nCom carinho\n{{consultor_nome}}\nConsultor de viagens',
    'referral-soft',
    'master-card-v1',
    'bottom-right',
    true,
    24
  ),
  (
    'lembrete-passaporte',
    'Lembrete importante',
    'utilidade',
    'Template de lembrete de passaporte',
    'cliente',
    E'{{cliente_nome}},\n\nPassando para lembrar\nde verificar a validade do seu passaporte\npara futuras viagens.\n\nSe precisar de ajuda, conte comigo.\n\n{{consultor_nome}}\nConsultor de viagens',
    'document-reminder-clean',
    'master-card-v1',
    'bottom-right',
    true,
    25
  ),
  (
    'lembrete-documentacao',
    'Atenção à documentação',
    'utilidade',
    'Template de lembrete de documentação',
    'cliente',
    E'{{cliente_nome}},\n\nAntes da próxima viagem,\nvale conferir toda a documentação necessária\npara embarcar com tranquilidade.\n\nSe quiser, posso te orientar.\n\n{{consultor_nome}}\nConsultor de viagens',
    'document-reminder-clean',
    'master-card-v1',
    'bottom-right',
    true,
    26
  ),
  (
    'campanha-sazonal',
    'Hora de planejar sua próxima viagem',
    'campanha',
    'Template de campanha sazonal',
    'cliente',
    E'{{cliente_nome}},\n\nTemos uma campanha especial no ar\ne pode haver uma ótima oportunidade\npara o seu próximo destino.\n\nSe quiser, te mostro as melhores opções.\n\n{{consultor_nome}}\nConsultor de viagens',
    'seasonal-campaign',
    'master-card-v1',
    'bottom-right',
    true,
    27
  ),
  (
    'feriado-prolongado',
    'Feriado chegando!',
    'oportunidade',
    'Template de feriado prolongado',
    'cliente',
    E'{{cliente_nome}},\n\nUm feriado prolongado\npode ser a oportunidade ideal\npara uma viagem rápida e especial.\n\nSe quiser sugestões, estou à disposição.\n\n{{consultor_nome}}\nConsultor de viagens',
    'long-holiday',
    'master-card-v1',
    'bottom-right',
    true,
    28
  ),
  (
    'oferta-recompra',
    'Vamos planejar a próxima?',
    'recompra',
    'Template de oferta para recompra',
    'cliente',
    E'{{cliente_nome}},\n\nDepois de uma boa viagem,\nsempre nasce a vontade da próxima.\n\nQuando quiser, posso te ajudar\na planejar um novo roteiro.\n\n{{consultor_nome}}\nConsultor de viagens',
    'repurchase-soft',
    'master-card-v1',
    'bottom-right',
    true,
    29
  ),
  (
    'data-especial-personalizada',
    'Uma data especial',
    'relacionamento',
    'Template genérico para data especial',
    'cliente',
    E'{{cliente_nome}},\n\nHoje é uma data especial\ne não poderia deixar\nde te enviar uma mensagem\ncom carinho.\n\nDesejo momentos felizes\ne experiências incríveis!\n\nCom carinho\n{{consultor_nome}}\nConsultor de viagens',
    'special-date-soft',
    'master-card-v1',
    'bottom-right',
    true,
    30
  )
on conflict (slug) do update
set
  title = excluded.title,
  category = excluded.category,
  description = excluded.description,
  subject_type = excluded.subject_type,
  message_template = excluded.message_template,
  theme_key = excluded.theme_key,
  layout_key = excluded.layout_key,
  logo_position = excluded.logo_position,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order,
  updated_at = now();
